import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { bundledDir, codexHome, findProjectRoot } from "../core/paths.js";

/**
 * Ship goat's role cards as Codex agent roles.
 *
 * Codex (from 0.115.0, codex-rs/core/src/config/agent_roles.rs; the loader moved to
 * codex-rs/agent-roles in 0.150.0) loads `<config folder>/agents/*.toml` from each enabled
 * config layer and exposes every role as an `agent_type` on `spawn_agent`. A project's
 * `.codex` layer is disabled when Codex does not trust the project, so project-scope role
 * files are inert there. The file is `name`, `description`,
 * `nickname_candidates`, plus any Codex config key — `developer_instructions` is the one
 * that carries the role — and unknown keys are rejected (`deny_unknown_fields`).
 *
 * Two facts shape the design. First, `agent_type` is removed from the spawn schema when no
 * user-defined role exists (core/src/tools/spec_plan.rs `expose_agent_type`), so without
 * these files a `$team` lane cannot be typed at all. Second, the cards are alternatives
 * to the skill bodies, never layers on them: `prompts/reviewer.md` is the whole brief for a
 * reviewer agent, which is exactly what a role's developer instructions are.
 *
 * Opt-in. Every role adds its name and description to the spawn tool's schema on every
 * turn of every session, which is a cost a user should choose.
 */

export const ROLE_FILE_MARKER = "# generated by codex-goat; `goat roles uninstall` removes it";

export type RoleScope = "user" | "project";

export interface RoleCard {
  /** File stem under prompts/, and the `agent_type` the model will use. */
  name: string;
  /** First sentence of the card, for the spawn tool's schema. */
  description: string;
  /** The whole card: this is the agent's developer message. */
  developerInstructions: string;
}

export function agentRolesDir(scope: RoleScope, cwd: string = process.cwd()): string {
  return scope === "user" ? join(codexHome(), "agents") : join(findProjectRoot(cwd), ".codex", "agents");
}

/** Every bundled role card, read from prompts/. */
export function roleCards(promptsDir: string = bundledDir("prompts")): RoleCard[] {
  return readdirSync(promptsDir)
    .filter((file) => file.endsWith(".md"))
    .sort()
    .map((file) => {
      const body = readFileSync(join(promptsDir, file), "utf8").trim();
      return { name: basename(file, ".md"), description: firstSentence(body), developerInstructions: body };
    });
}

/**
 * The first prose line after the title, cut at its first sentence. Cards open with a
 * one-line statement of the role ("You judge a diff.") that reads well in a schema.
 */
function firstSentence(body: string): string {
  const line = body
    .split(/\r?\n/)
    .map((entry) => entry.trim())
    .find((entry) => entry.length > 0 && !entry.startsWith("#"));
  if (!line) return "";
  const end = line.search(/[.!?](\s|$)/);
  return end === -1 ? line : line.slice(0, end + 1);
}

/** TOML for one role, with only keys Codex's role loader accepts. */
export function renderRoleToml(card: RoleCard): string {
  return [
    ROLE_FILE_MARKER,
    `name = ${tomlBasic(card.name)}`,
    `description = ${tomlBasic(card.description)}`,
    `developer_instructions = ${tomlMultiline(card.developerInstructions)}`,
    "",
  ].join("\n");
}

function tomlBasic(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

/**
 * A multi-line literal string carries the card verbatim: backticks, quotes and
 * backslashes need no escaping. The one thing it cannot hold is `'''`, so a card
 * containing it falls back to a basic string.
 */
function tomlMultiline(value: string): string {
  if (value.includes("'''")) return tomlBasic(value);
  return `'''\n${value.replace(/\s+$/, "")}\n'''`;
}

export interface RoleInstallReport {
  written: string[];
  skipped: string[];
}

/** Write one TOML per card, never over a file goat did not generate. */
export function installAgentRoles(dir: string, cards: RoleCard[] = roleCards()): RoleInstallReport {
  mkdirSync(dir, { recursive: true });
  const report: RoleInstallReport = { written: [], skipped: [] };
  for (const card of cards) {
    const file = join(dir, `${card.name}.toml`);
    if (existsSync(file) && !isGoatRoleFile(file)) {
      report.skipped.push(file);
      continue;
    }
    writeFileSync(file, renderRoleToml(card));
    report.written.push(file);
  }
  return report;
}

/** Remove every goat-generated role file in `dir`; leave everything else alone. */
export function uninstallAgentRoles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const removed: string[] = [];
  for (const file of readdirSync(dir)) {
    const path = join(dir, file);
    if (file.endsWith(".toml") && isGoatRoleFile(path)) {
      rmSync(path);
      removed.push(path);
    }
  }
  return removed;
}

export function installedGoatRoles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((file) => file.endsWith(".toml") && isGoatRoleFile(join(dir, file)))
    .map((file) => basename(file, ".toml"))
    .sort();
}

function isGoatRoleFile(path: string): boolean {
  try {
    return readFileSync(path, "utf8").startsWith(ROLE_FILE_MARKER);
  } catch {
    return false;
  }
}
