import { GoatError, log } from "../../core/log.js";
import { agentRolesDir, installAgentRoles, installedGoatRoles, roleCards, type RoleScope, uninstallAgentRoles } from "../../setup/agent-roles.js";
import { compareVersions } from "../../state/routing.js";
import type { ParsedArgs } from "../args.js";
import { flagString } from "../args.js";
import { codexVersion } from "../launch.js";

/**
 * First Codex release that discovers `<config>/agents/*.toml` role files
 * (codex-rs/core/src/config/agent_roles.rs at rust-v0.115.0; the loader moved into the
 * codex-rs/agent-roles crate in 0.150.0 with the same file schema).
 */
export const AGENT_ROLES_MIN_CODEX = "0.115.0";

/**
 * `goat roles install|uninstall|list [--scope user|project]`
 *
 * Opt-in on purpose: every installed role adds its name and description to the
 * `spawn_agent` schema on every turn. Nothing else in goat assumes these files exist —
 * `$team` omits `agent_type` unless the tool lists roles, and `goat exec --role` reads the
 * cards straight from prompts/.
 */
export function runRoles(parsed: ParsedArgs, cwd: string = process.cwd()): number {
  const action = parsed.positionals[0] ?? "list";
  const scopeFlag = flagString(parsed.flags, "scope") ?? "project";
  if (scopeFlag !== "user" && scopeFlag !== "project") {
    throw new GoatError(`Unknown --scope '${scopeFlag}'.`, "Use --scope user or --scope project.");
  }
  const scope: RoleScope = scopeFlag;
  const dir = agentRolesDir(scope, cwd);

  switch (action) {
    case "install": {
      const report = installAgentRoles(dir);
      for (const file of report.written) log.detail(`wrote ${file}`);
      for (const file of report.skipped) log.warn(`${file} exists and was not generated by goat; skipped`);
      log.ok(`${report.written.length} agent role(s) installed in ${dir} (${scope} scope)`);
      warnIfCodexTooOld();
      log.detail("spawn_agent now offers these as agent_type; `goat roles uninstall` removes them");
      if (scope === "project") {
        log.detail("project-scope roles load only in a project Codex trusts; an untrusted checkout ignores its .codex layer");
      }
      return 0;
    }
    case "uninstall": {
      const removed = uninstallAgentRoles(dir);
      for (const file of removed) log.detail(`removed ${file}`);
      log.ok(`${removed.length} goat agent role(s) removed from ${dir}`);
      return 0;
    }
    case "list": {
      const installed = new Set(installedGoatRoles(dir));
      log.out(`agent roles (${scope} scope, ${dir})`);
      for (const card of roleCards()) {
        log.out(`  ${card.name.padEnd(18)} ${installed.has(card.name) ? "installed" : "not installed"}  ${card.description}`);
      }
      if (installed.size === 0) log.detail("install with: goat roles install [--scope user|project]");
      warnIfCodexTooOld();
      return 0;
    }
    default:
      throw new GoatError(`Unknown roles action '${action}'.`, "Use: goat roles install | uninstall | list");
  }
}

function warnIfCodexTooOld(): void {
  // codexVersion() throws when no codex is resolvable; a missing Codex must not turn a
  // completed install into an error exit.
  let installed: string | null = null;
  try {
    installed = codexVersion();
  } catch {
    installed = null;
  }
  if (installed === null) {
    log.warn(`could not read the Codex version; agent roles need Codex >= ${AGENT_ROLES_MIN_CODEX}`);
  } else if (compareVersions(installed, AGENT_ROLES_MIN_CODEX) < 0) {
    log.warn(`Codex ${installed} ignores agent role files; they load from ${AGENT_ROLES_MIN_CODEX}`);
  }
}
